### ISSUE TITLE
Add support for version-controlled rasters

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#794]
Tracking bug - will add PRs here, and make notes of functionality that is missing. Later when rasters gets closer to launch, this can be used to file individual raster issues.

Some bullet points:

- [x] Basic import from geotiff - extract metadata from geotiff, write as Kart a dataset
- [x] Diffing: commit<>commit
- [x] Diffing: commit<>working copy
- [x] Diffs can be committed
- [x] Support for datasets that are constrained to be COG, vs datasets that are just geotiff
- [x] Support for convert-to-COG during import
- [x] Support for convert-to-COG during diff / commit
- [x] Spatial filters working

Maybe: any more conversions supported? Any relaxable constraints eg "optional alpha band"?

**Comment by olsen232** [comment]
The gdal module is already included in the Kart build, which is useful - but tests are failing on CI on macos due to a crash in the gdal module which we'll need to investigate:
```
  1: tests/raster/test_imports.py::test_import_single_geotiff Fatal Python error: Aborted
  
  1: Current thread 0x000000011c82e600 (most recent call first):
  1:   File "/Users/runner/work/kart/kart/build/venv/lib/python3.10/site-packages/osgeo/gdal.py", line 4757 in InfoInternal
  1:   File "/Users/runner/work/kart/kart/build/venv/lib/python3.10/site-packages/osgeo/gdal.py", line 248 in Info
  1:   File "/Users/runner/work/kart/kart/tests/raster/fixtures.py", line 14 in requires_gdal_info
```
Not much useful info there

**Comment by olsen232** [comment]
- category-tables and band descriptions are now imported / exposed as meta items, as are RAT headings
- color tables are not imported (or at least not exposed as meta items) - there's no guarantee they'll be homogenous across the dataset

Some missing bits to come back to:
- category-tables aren't merged well - if one of your tiles is missing some of the categories, it will conflict with the others. Certain tiles missing certain categories should be allowed.
- spatial filtering doesn't affect PAM files - all PAM files match the spatial filter.

**Comment by olsen232** [comment]
PAM files are now editable and committable, including the meta items - category-tables, RAT headings

Some missing bits to come back to:
Changing the number of meta items changes during a diff / commit is not handled properly - eg if you delete all the PAM files and try to commit, it will crash as it tries to go from some category-tables to no category tables.

**Comment by olsen232** [comment]
More work to do with respect to informing / prompting / warning the user about cloud-optimized vs non-cloud-optimized tiles - both for rasters and point clouds:

Import behaviour:
[ ] Import with --convert-to-cog: no warning
[ ] Import with --no-convert-to-cog: no warning

[ ] Import with no flag and some non-COGS and atty():
"... Would you like to convert your files to be cloud optimized?"
[ ] Import with no flag and all COGs and atty()
"... Would you like to constrain your dataset to be cloud-optimized"

[ ] Import with no flag and some non-COGs and no atty():
"Run this command again with --convert-to-cog or --preserve-format."
[ ] Import this no flag and all COGs and atty():
"Run this command again with --convert-to-cog or --preserve-format."

Diff/commit behaviour: wrong cloud-optimizedness
[ ] Diff/commit to preserve-format dataset: no warnings are shown.
[ ] Diff/commit COG to cloud-optimized dataset: no warnings are shown.
[ ] Diff/commit non-COG to convert-to-cog dataset, no flag - shows warning during diff or commit, prevents commit.
    "Adding non-COG files to a cloud-optimized dataset is not allowed. Add --convert-to-dataset-format flag to cloud-optimize the files, or add --no-convert-to-dataset-format to remove the dataset constraints."
[ ] Diff/commit non-COG to convert-to-cog dataset, --convert-to-dataset-format: files are automatically converted.
[ ] Diff/commit non-COG files to convert-to-cog dataset, --no-convert-to-dataset-format: dataset constraint is removed.

Diff/commit behaviour: Wrong LAZ version:
[ ] Diff/commit non-COG to convert-to-cog dataset, no flag - shows warning during diff or commit, prevents commit.
    "Adding multiple LAZ versions in the same dataset is not allowed. Add --convert-to-dataset-format flag to automatically convert them to the dataset's LAZ version."
