### ISSUE TITLE
Tracking bug for `kart export` command

### ISSUE THREAD

**Issue by olsen232** [koordinates/kart#992]
`kart import` lets you take a non-Kart dataset and import it to Kart.
There's no opposite command that takes a Kart dataset and exports it as some non-kart dataset type.

(Except that, if you really need to, you can use the working-copy creation functionality to export a dataset, or, use ogr2ogr on the contents of your working copy, or use ogr2ogr plus the experimental OGR driver in checked into `contrib/`.

This is the tracking bug for adding a `kart export` command. It will use GDAL OGR drivers internally and so will immediately support export to most anything that OGR supports, and it will feel familiar for anyone used to using ogr2ogr.

A downside to this approach is that we might have a bit more OGR behaviour / bugs than we want, until and unless we special case them or work around them. For example:
- Connection strings for postgres / MSSQL drivers will have to be in the format that OGR expects, not the format that Kart expects.
- OGR's type system doesn't have NUMERIC as a separate type from INTEGER / FLOAT, so handling of these types tends to be a bit inconsistent - this is one reason that `kart import` mostly doesn't use OGR any more.

**Comment by olsen232** [comment]
Implemented in the following PRs:
#988
#990
#991

**Comment by olsen232** [comment]
Mostly done except I should update the docs at https://docs.kartproject.org/en/latest/pages/command_reference.html

Possible future enhancements: 
- export for raster and point clouds
- export lots of things at once eg `kart export --all-tables`
- prevent the user (or at least warn them against) exporting data into the working copy that kart is already maintaining

**Comment by craigds** [comment]
I've experimented a bit with this and had a few issues/suggestions:
 
* [ ] `kart export --help` shows no options (you have to `kart table-export --help`). why are there two since it only supports tables anyway
* [ ] need a way to select an export format - it seems to auto-detect based on file extension, but no way to override
* [ ] VSI URLs work as an export dest 🎉 but would work better if we set `CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE=YES` (GDAL tells you this if you try to export to a `/vsis3/bucketname/file.fgb`)
* [ ] should support `-` as an easy way of exporting to stdout (for streamable export formats anyway) - just wrap `/vsistdout/`

**Comment by olsen232** [comment]
> need a way to select an export format - it seems to auto-detect based on file extension, but no way to override

This isn't well documented but `kart export --help` says the command format is:
`kart export [OPTIONS] DATASET [EXPORT_TYPE:]DESTINATION`

so, for example, `GPKG:output.db` would work. But yes this should be clarified
